#!/bin/bash
# Embeds the runtime C sources and the Nomu prelude into a Swift file as raw string
# constants, so nomuc stays a single relocatable binary while the .c/.h/.nomu files
# remain the editable source of truth (M4.13; m4.13-spec.md §3). Raw Swift strings
# (##"""…"""##) mean the file contents pass through verbatim — no escaping.
set -euo pipefail

out="$1"; rt_h="$2"; rt_c="$3"; core_c="$4"; prelude="$5"

emit() {  # $1 = Swift constant name, $2 = source file
    printf '    public static let %s = ##"""\n' "$1"
    cat "$2"
    printf '\n"""##\n'
}

{
    echo '// GENERATED by src/runtime/embed.sh — do not edit.'
    echo '// Source of truth: src/runtime/*.c, *.h and src/stdlib/*.nomu.'
    echo 'public enum EmbeddedSources {'
    emit runtimeHeader "$rt_h"
    emit runtimeC "$rt_c"
    emit coreC "$core_c"
    echo '    public static let preludeName = "core.nomu"'
    emit preludeSource "$prelude"
    echo '}'
} > "$out"
